//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from BetterAdvGm.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.CLSCompliant(false)]
public partial class BetterAdvGmLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		WHITESPACE=1, KEYWORD_TEXT=2, KEYWORD_STRING=3, END_STMT=4, STRING=5, 
		TRAVEL_KEYWORD=6, INCREMENT=7, CURLY_LEFT=8, CURLY_RIGHT=9, PAREN_LEFT=10, 
		PAREN_RIGHT=11, SQUARE_LEFT=12, SQUARE_RIGHT=13, KEYWORD_INPUT=14, KEYWORD_INT=15, 
		KEYWORD_IF=16, KEYWORD_ELSE=17, KEYWORD_ELSEIF=18, KEYWORD_WHILE=19, KEYWORD_FOR=20, 
		KEYWORD_LOCATION=21, KEYWORD_SETUP=22, KEYWORD_LOCATIONARRAY=23, KEYWORD_LOCATIONS=24, 
		KEYWORD_CHOICE=25, COMMA_SEPERATOR=26, CMP_OPERATOR=27, ASSIGN_OPERATOR=28, 
		COMPOUND_OPERATOR=29, TIMES_OPERATOR=30, DIVISION_OPERATOR=31, PLUS_OPERATOR=32, 
		MINUS_OPERATOR=33, ARROW_OPERATOR=34, AND_OPERATOR=35, OR_OPERATOR=36, 
		NUM=37, VAR_NAME=38;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"LETTERS", "WHITESPACE", "KEYWORD_TEXT", "KEYWORD_STRING", "END_STMT", 
		"STRING", "TRAVEL_KEYWORD", "INCREMENT", "CURLY_LEFT", "CURLY_RIGHT", 
		"PAREN_LEFT", "PAREN_RIGHT", "SQUARE_LEFT", "SQUARE_RIGHT", "KEYWORD_INPUT", 
		"KEYWORD_INT", "KEYWORD_IF", "KEYWORD_ELSE", "KEYWORD_ELSEIF", "KEYWORD_WHILE", 
		"KEYWORD_FOR", "KEYWORD_LOCATION", "KEYWORD_SETUP", "KEYWORD_LOCATIONARRAY", 
		"KEYWORD_LOCATIONS", "KEYWORD_CHOICE", "COMMA_SEPERATOR", "CMP_OPERATOR", 
		"ASSIGN_OPERATOR", "COMPOUND_OPERATOR", "TIMES_OPERATOR", "DIVISION_OPERATOR", 
		"PLUS_OPERATOR", "MINUS_OPERATOR", "ARROW_OPERATOR", "AND_OPERATOR", "OR_OPERATOR", 
		"NUM", "VAR_NAME"
	};


	public BetterAdvGmLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public BetterAdvGmLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, "'Text '", "'string '", "';'", null, "'Travel '", "'++'", 
		"'{'", "'}'", "'('", "')'", "'['", "']'", "'userInput'", "'int'", "'if'", 
		"'else'", "'else if'", "'while'", "'for'", "'Location'", "'setup'", "'LocationArray'", 
		"'Locations'", "'choice'", "','", null, "'='", "'+='", "'*'", "'/'", "'+'", 
		"'-'", "'->'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "WHITESPACE", "KEYWORD_TEXT", "KEYWORD_STRING", "END_STMT", "STRING", 
		"TRAVEL_KEYWORD", "INCREMENT", "CURLY_LEFT", "CURLY_RIGHT", "PAREN_LEFT", 
		"PAREN_RIGHT", "SQUARE_LEFT", "SQUARE_RIGHT", "KEYWORD_INPUT", "KEYWORD_INT", 
		"KEYWORD_IF", "KEYWORD_ELSE", "KEYWORD_ELSEIF", "KEYWORD_WHILE", "KEYWORD_FOR", 
		"KEYWORD_LOCATION", "KEYWORD_SETUP", "KEYWORD_LOCATIONARRAY", "KEYWORD_LOCATIONS", 
		"KEYWORD_CHOICE", "COMMA_SEPERATOR", "CMP_OPERATOR", "ASSIGN_OPERATOR", 
		"COMPOUND_OPERATOR", "TIMES_OPERATOR", "DIVISION_OPERATOR", "PLUS_OPERATOR", 
		"MINUS_OPERATOR", "ARROW_OPERATOR", "AND_OPERATOR", "OR_OPERATOR", "NUM", 
		"VAR_NAME"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "BetterAdvGm.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static BetterAdvGmLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '(', '\x136', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x4', '&', 
		'\t', '&', '\x4', '\'', '\t', '\'', '\x4', '(', '\t', '(', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x3', '\x6', '\x3', 'U', '\n', '\x3', '\r', '\x3', 
		'\xE', '\x3', 'V', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', 
		'\a', '\a', '\a', 'm', '\n', '\a', '\f', '\a', '\xE', '\a', 'p', '\v', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', 
		'\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', 
		'\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', 
		'\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', 
		'\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x5', '\x1D', '\x108', 
		'\n', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', '\x3', '\x1F', 
		'\x3', '\x1F', '\x3', ' ', '\x3', ' ', '\x3', '!', '\x3', '!', '\x3', 
		'\"', '\x3', '\"', '\x3', '#', '\x3', '#', '\x3', '$', '\x3', '$', '\x3', 
		'$', '\x3', '%', '\x3', '%', '\x3', '%', '\x3', '%', '\x3', '%', '\x3', 
		'%', '\x3', '%', '\x3', '%', '\x5', '%', '\x122', '\n', '%', '\x3', '&', 
		'\x3', '&', '\x3', '&', '\x3', '&', '\x3', '&', '\x3', '&', '\x5', '&', 
		'\x12A', '\n', '&', '\x3', '\'', '\x6', '\'', '\x12D', '\n', '\'', '\r', 
		'\'', '\xE', '\'', '\x12E', '\x3', '(', '\x3', '(', '\x6', '(', '\x133', 
		'\n', '(', '\r', '(', '\xE', '(', '\x134', '\x2', '\x2', ')', '\x3', '\x2', 
		'\x5', '\x3', '\a', '\x4', '\t', '\x5', '\v', '\x6', '\r', '\a', '\xF', 
		'\b', '\x11', '\t', '\x13', '\n', '\x15', '\v', '\x17', '\f', '\x19', 
		'\r', '\x1B', '\xE', '\x1D', '\xF', '\x1F', '\x10', '!', '\x11', '#', 
		'\x12', '%', '\x13', '\'', '\x14', ')', '\x15', '+', '\x16', '-', '\x17', 
		'/', '\x18', '\x31', '\x19', '\x33', '\x1A', '\x35', '\x1B', '\x37', '\x1C', 
		'\x39', '\x1D', ';', '\x1E', '=', '\x1F', '?', ' ', '\x41', '!', '\x43', 
		'\"', '\x45', '#', 'G', '$', 'I', '%', 'K', '&', 'M', '\'', 'O', '(', 
		'\x3', '\x2', '\x6', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x5', '\x2', 
		'\v', '\f', '\xF', '\xF', '\"', '\"', '\x3', '\x2', '$', '$', '\x3', '\x2', 
		'\x32', ';', '\x2', '\x143', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x2', '\x37', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x39', '\x3', '\x2', '\x2', '\x2', '\x2', 
		';', '\x3', '\x2', '\x2', '\x2', '\x2', '=', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '?', '\x3', '\x2', '\x2', '\x2', '\x2', '\x41', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x43', '\x3', '\x2', '\x2', '\x2', '\x2', '\x45', '\x3', 
		'\x2', '\x2', '\x2', '\x2', 'G', '\x3', '\x2', '\x2', '\x2', '\x2', 'I', 
		'\x3', '\x2', '\x2', '\x2', '\x2', 'K', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'M', '\x3', '\x2', '\x2', '\x2', '\x2', 'O', '\x3', '\x2', '\x2', '\x2', 
		'\x3', 'Q', '\x3', '\x2', '\x2', '\x2', '\x5', 'T', '\x3', '\x2', '\x2', 
		'\x2', '\a', 'Z', '\x3', '\x2', '\x2', '\x2', '\t', '`', '\x3', '\x2', 
		'\x2', '\x2', '\v', 'h', '\x3', '\x2', '\x2', '\x2', '\r', 'j', '\x3', 
		'\x2', '\x2', '\x2', '\xF', 's', '\x3', '\x2', '\x2', '\x2', '\x11', '{', 
		'\x3', '\x2', '\x2', '\x2', '\x13', '~', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'\x80', '\x3', '\x2', '\x2', '\x2', '\x17', '\x82', '\x3', '\x2', '\x2', 
		'\x2', '\x19', '\x84', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x86', '\x3', 
		'\x2', '\x2', '\x2', '\x1D', '\x88', '\x3', '\x2', '\x2', '\x2', '\x1F', 
		'\x8A', '\x3', '\x2', '\x2', '\x2', '!', '\x94', '\x3', '\x2', '\x2', 
		'\x2', '#', '\x98', '\x3', '\x2', '\x2', '\x2', '%', '\x9B', '\x3', '\x2', 
		'\x2', '\x2', '\'', '\xA0', '\x3', '\x2', '\x2', '\x2', ')', '\xA8', '\x3', 
		'\x2', '\x2', '\x2', '+', '\xAE', '\x3', '\x2', '\x2', '\x2', '-', '\xB2', 
		'\x3', '\x2', '\x2', '\x2', '/', '\xBB', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'\xC1', '\x3', '\x2', '\x2', '\x2', '\x33', '\xCF', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\xD9', '\x3', '\x2', '\x2', '\x2', '\x37', '\xE0', '\x3', 
		'\x2', '\x2', '\x2', '\x39', '\x107', '\x3', '\x2', '\x2', '\x2', ';', 
		'\x109', '\x3', '\x2', '\x2', '\x2', '=', '\x10B', '\x3', '\x2', '\x2', 
		'\x2', '?', '\x10E', '\x3', '\x2', '\x2', '\x2', '\x41', '\x110', '\x3', 
		'\x2', '\x2', '\x2', '\x43', '\x112', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\x114', '\x3', '\x2', '\x2', '\x2', 'G', '\x116', '\x3', '\x2', '\x2', 
		'\x2', 'I', '\x121', '\x3', '\x2', '\x2', '\x2', 'K', '\x129', '\x3', 
		'\x2', '\x2', '\x2', 'M', '\x12C', '\x3', '\x2', '\x2', '\x2', 'O', '\x132', 
		'\x3', '\x2', '\x2', '\x2', 'Q', 'R', '\t', '\x2', '\x2', '\x2', 'R', 
		'\x4', '\x3', '\x2', '\x2', '\x2', 'S', 'U', '\t', '\x3', '\x2', '\x2', 
		'T', 'S', '\x3', '\x2', '\x2', '\x2', 'U', 'V', '\x3', '\x2', '\x2', '\x2', 
		'V', 'T', '\x3', '\x2', '\x2', '\x2', 'V', 'W', '\x3', '\x2', '\x2', '\x2', 
		'W', 'X', '\x3', '\x2', '\x2', '\x2', 'X', 'Y', '\b', '\x3', '\x2', '\x2', 
		'Y', '\x6', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\a', 'V', '\x2', '\x2', 
		'[', '\\', '\a', 'g', '\x2', '\x2', '\\', ']', '\a', 'z', '\x2', '\x2', 
		']', '^', '\a', 'v', '\x2', '\x2', '^', '_', '\a', '\"', '\x2', '\x2', 
		'_', '\b', '\x3', '\x2', '\x2', '\x2', '`', '\x61', '\a', 'u', '\x2', 
		'\x2', '\x61', '\x62', '\a', 'v', '\x2', '\x2', '\x62', '\x63', '\a', 
		't', '\x2', '\x2', '\x63', '\x64', '\a', 'k', '\x2', '\x2', '\x64', '\x65', 
		'\a', 'p', '\x2', '\x2', '\x65', '\x66', '\a', 'i', '\x2', '\x2', '\x66', 
		'g', '\a', '\"', '\x2', '\x2', 'g', '\n', '\x3', '\x2', '\x2', '\x2', 
		'h', 'i', '\a', '=', '\x2', '\x2', 'i', '\f', '\x3', '\x2', '\x2', '\x2', 
		'j', 'n', '\a', '$', '\x2', '\x2', 'k', 'm', '\n', '\x4', '\x2', '\x2', 
		'l', 'k', '\x3', '\x2', '\x2', '\x2', 'm', 'p', '\x3', '\x2', '\x2', '\x2', 
		'n', 'l', '\x3', '\x2', '\x2', '\x2', 'n', 'o', '\x3', '\x2', '\x2', '\x2', 
		'o', 'q', '\x3', '\x2', '\x2', '\x2', 'p', 'n', '\x3', '\x2', '\x2', '\x2', 
		'q', 'r', '\a', '$', '\x2', '\x2', 'r', '\xE', '\x3', '\x2', '\x2', '\x2', 
		's', 't', '\a', 'V', '\x2', '\x2', 't', 'u', '\a', 't', '\x2', '\x2', 
		'u', 'v', '\a', '\x63', '\x2', '\x2', 'v', 'w', '\a', 'x', '\x2', '\x2', 
		'w', 'x', '\a', 'g', '\x2', '\x2', 'x', 'y', '\a', 'n', '\x2', '\x2', 
		'y', 'z', '\a', '\"', '\x2', '\x2', 'z', '\x10', '\x3', '\x2', '\x2', 
		'\x2', '{', '|', '\a', '-', '\x2', '\x2', '|', '}', '\a', '-', '\x2', 
		'\x2', '}', '\x12', '\x3', '\x2', '\x2', '\x2', '~', '\x7F', '\a', '}', 
		'\x2', '\x2', '\x7F', '\x14', '\x3', '\x2', '\x2', '\x2', '\x80', '\x81', 
		'\a', '\x7F', '\x2', '\x2', '\x81', '\x16', '\x3', '\x2', '\x2', '\x2', 
		'\x82', '\x83', '\a', '*', '\x2', '\x2', '\x83', '\x18', '\x3', '\x2', 
		'\x2', '\x2', '\x84', '\x85', '\a', '+', '\x2', '\x2', '\x85', '\x1A', 
		'\x3', '\x2', '\x2', '\x2', '\x86', '\x87', '\a', ']', '\x2', '\x2', '\x87', 
		'\x1C', '\x3', '\x2', '\x2', '\x2', '\x88', '\x89', '\a', '_', '\x2', 
		'\x2', '\x89', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\a', 
		'w', '\x2', '\x2', '\x8B', '\x8C', '\a', 'u', '\x2', '\x2', '\x8C', '\x8D', 
		'\a', 'g', '\x2', '\x2', '\x8D', '\x8E', '\a', 't', '\x2', '\x2', '\x8E', 
		'\x8F', '\a', 'K', '\x2', '\x2', '\x8F', '\x90', '\a', 'p', '\x2', '\x2', 
		'\x90', '\x91', '\a', 'r', '\x2', '\x2', '\x91', '\x92', '\a', 'w', '\x2', 
		'\x2', '\x92', '\x93', '\a', 'v', '\x2', '\x2', '\x93', ' ', '\x3', '\x2', 
		'\x2', '\x2', '\x94', '\x95', '\a', 'k', '\x2', '\x2', '\x95', '\x96', 
		'\a', 'p', '\x2', '\x2', '\x96', '\x97', '\a', 'v', '\x2', '\x2', '\x97', 
		'\"', '\x3', '\x2', '\x2', '\x2', '\x98', '\x99', '\a', 'k', '\x2', '\x2', 
		'\x99', '\x9A', '\a', 'h', '\x2', '\x2', '\x9A', '$', '\x3', '\x2', '\x2', 
		'\x2', '\x9B', '\x9C', '\a', 'g', '\x2', '\x2', '\x9C', '\x9D', '\a', 
		'n', '\x2', '\x2', '\x9D', '\x9E', '\a', 'u', '\x2', '\x2', '\x9E', '\x9F', 
		'\a', 'g', '\x2', '\x2', '\x9F', '&', '\x3', '\x2', '\x2', '\x2', '\xA0', 
		'\xA1', '\a', 'g', '\x2', '\x2', '\xA1', '\xA2', '\a', 'n', '\x2', '\x2', 
		'\xA2', '\xA3', '\a', 'u', '\x2', '\x2', '\xA3', '\xA4', '\a', 'g', '\x2', 
		'\x2', '\xA4', '\xA5', '\a', '\"', '\x2', '\x2', '\xA5', '\xA6', '\a', 
		'k', '\x2', '\x2', '\xA6', '\xA7', '\a', 'h', '\x2', '\x2', '\xA7', '(', 
		'\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\a', 'y', '\x2', '\x2', '\xA9', 
		'\xAA', '\a', 'j', '\x2', '\x2', '\xAA', '\xAB', '\a', 'k', '\x2', '\x2', 
		'\xAB', '\xAC', '\a', 'n', '\x2', '\x2', '\xAC', '\xAD', '\a', 'g', '\x2', 
		'\x2', '\xAD', '*', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xAF', '\a', 
		'h', '\x2', '\x2', '\xAF', '\xB0', '\a', 'q', '\x2', '\x2', '\xB0', '\xB1', 
		'\a', 't', '\x2', '\x2', '\xB1', ',', '\x3', '\x2', '\x2', '\x2', '\xB2', 
		'\xB3', '\a', 'N', '\x2', '\x2', '\xB3', '\xB4', '\a', 'q', '\x2', '\x2', 
		'\xB4', '\xB5', '\a', '\x65', '\x2', '\x2', '\xB5', '\xB6', '\a', '\x63', 
		'\x2', '\x2', '\xB6', '\xB7', '\a', 'v', '\x2', '\x2', '\xB7', '\xB8', 
		'\a', 'k', '\x2', '\x2', '\xB8', '\xB9', '\a', 'q', '\x2', '\x2', '\xB9', 
		'\xBA', '\a', 'p', '\x2', '\x2', '\xBA', '.', '\x3', '\x2', '\x2', '\x2', 
		'\xBB', '\xBC', '\a', 'u', '\x2', '\x2', '\xBC', '\xBD', '\a', 'g', '\x2', 
		'\x2', '\xBD', '\xBE', '\a', 'v', '\x2', '\x2', '\xBE', '\xBF', '\a', 
		'w', '\x2', '\x2', '\xBF', '\xC0', '\a', 'r', '\x2', '\x2', '\xC0', '\x30', 
		'\x3', '\x2', '\x2', '\x2', '\xC1', '\xC2', '\a', 'N', '\x2', '\x2', '\xC2', 
		'\xC3', '\a', 'q', '\x2', '\x2', '\xC3', '\xC4', '\a', '\x65', '\x2', 
		'\x2', '\xC4', '\xC5', '\a', '\x63', '\x2', '\x2', '\xC5', '\xC6', '\a', 
		'v', '\x2', '\x2', '\xC6', '\xC7', '\a', 'k', '\x2', '\x2', '\xC7', '\xC8', 
		'\a', 'q', '\x2', '\x2', '\xC8', '\xC9', '\a', 'p', '\x2', '\x2', '\xC9', 
		'\xCA', '\a', '\x43', '\x2', '\x2', '\xCA', '\xCB', '\a', 't', '\x2', 
		'\x2', '\xCB', '\xCC', '\a', 't', '\x2', '\x2', '\xCC', '\xCD', '\a', 
		'\x63', '\x2', '\x2', '\xCD', '\xCE', '\a', '{', '\x2', '\x2', '\xCE', 
		'\x32', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xD0', '\a', 'N', '\x2', 
		'\x2', '\xD0', '\xD1', '\a', 'q', '\x2', '\x2', '\xD1', '\xD2', '\a', 
		'\x65', '\x2', '\x2', '\xD2', '\xD3', '\a', '\x63', '\x2', '\x2', '\xD3', 
		'\xD4', '\a', 'v', '\x2', '\x2', '\xD4', '\xD5', '\a', 'k', '\x2', '\x2', 
		'\xD5', '\xD6', '\a', 'q', '\x2', '\x2', '\xD6', '\xD7', '\a', 'p', '\x2', 
		'\x2', '\xD7', '\xD8', '\a', 'u', '\x2', '\x2', '\xD8', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\xD9', '\xDA', '\a', '\x65', '\x2', '\x2', '\xDA', 
		'\xDB', '\a', 'j', '\x2', '\x2', '\xDB', '\xDC', '\a', 'q', '\x2', '\x2', 
		'\xDC', '\xDD', '\a', 'k', '\x2', '\x2', '\xDD', '\xDE', '\a', '\x65', 
		'\x2', '\x2', '\xDE', '\xDF', '\a', 'g', '\x2', '\x2', '\xDF', '\x36', 
		'\x3', '\x2', '\x2', '\x2', '\xE0', '\xE1', '\a', '.', '\x2', '\x2', '\xE1', 
		'\x38', '\x3', '\x2', '\x2', '\x2', '\xE2', '\xE3', '\a', 'k', '\x2', 
		'\x2', '\xE3', '\x108', '\a', 'u', '\x2', '\x2', '\xE4', '\xE5', '\a', 
		'k', '\x2', '\x2', '\xE5', '\xE6', '\a', 'u', '\x2', '\x2', '\xE6', '\xE7', 
		'\a', '\"', '\x2', '\x2', '\xE7', '\xE8', '\a', 'p', '\x2', '\x2', '\xE8', 
		'\xE9', '\a', 'q', '\x2', '\x2', '\xE9', '\x108', '\a', 'v', '\x2', '\x2', 
		'\xEA', '\xEB', '\a', '?', '\x2', '\x2', '\xEB', '\x108', '\a', '?', '\x2', 
		'\x2', '\xEC', '\xED', '\a', 'i', '\x2', '\x2', '\xED', '\xEE', '\a', 
		't', '\x2', '\x2', '\xEE', '\xEF', '\a', 'g', '\x2', '\x2', '\xEF', '\xF0', 
		'\a', '\x63', '\x2', '\x2', '\xF0', '\xF1', '\a', 'v', '\x2', '\x2', '\xF1', 
		'\xF2', '\a', 'g', '\x2', '\x2', '\xF2', '\xF3', '\a', 't', '\x2', '\x2', 
		'\xF3', '\xF4', '\a', '\"', '\x2', '\x2', '\xF4', '\xF5', '\a', 'v', '\x2', 
		'\x2', '\xF5', '\xF6', '\a', 'j', '\x2', '\x2', '\xF6', '\xF7', '\a', 
		'\x63', '\x2', '\x2', '\xF7', '\x108', '\a', 'p', '\x2', '\x2', '\xF8', 
		'\xF9', '\a', 'n', '\x2', '\x2', '\xF9', '\xFA', '\a', 'g', '\x2', '\x2', 
		'\xFA', '\xFB', '\a', 'u', '\x2', '\x2', '\xFB', '\xFC', '\a', 'u', '\x2', 
		'\x2', '\xFC', '\xFD', '\a', 'g', '\x2', '\x2', '\xFD', '\xFE', '\a', 
		't', '\x2', '\x2', '\xFE', '\xFF', '\a', '\"', '\x2', '\x2', '\xFF', '\x100', 
		'\a', 'v', '\x2', '\x2', '\x100', '\x101', '\a', 'j', '\x2', '\x2', '\x101', 
		'\x102', '\a', '\x63', '\x2', '\x2', '\x102', '\x108', '\a', 'p', '\x2', 
		'\x2', '\x103', '\x104', '\a', '>', '\x2', '\x2', '\x104', '\x108', '\a', 
		'?', '\x2', '\x2', '\x105', '\x106', '\a', '@', '\x2', '\x2', '\x106', 
		'\x108', '\a', '?', '\x2', '\x2', '\x107', '\xE2', '\x3', '\x2', '\x2', 
		'\x2', '\x107', '\xE4', '\x3', '\x2', '\x2', '\x2', '\x107', '\xEA', '\x3', 
		'\x2', '\x2', '\x2', '\x107', '\xEC', '\x3', '\x2', '\x2', '\x2', '\x107', 
		'\xF8', '\x3', '\x2', '\x2', '\x2', '\x107', '\x103', '\x3', '\x2', '\x2', 
		'\x2', '\x107', '\x105', '\x3', '\x2', '\x2', '\x2', '\x108', ':', '\x3', 
		'\x2', '\x2', '\x2', '\x109', '\x10A', '\a', '?', '\x2', '\x2', '\x10A', 
		'<', '\x3', '\x2', '\x2', '\x2', '\x10B', '\x10C', '\a', '-', '\x2', '\x2', 
		'\x10C', '\x10D', '\a', '?', '\x2', '\x2', '\x10D', '>', '\x3', '\x2', 
		'\x2', '\x2', '\x10E', '\x10F', '\a', ',', '\x2', '\x2', '\x10F', '@', 
		'\x3', '\x2', '\x2', '\x2', '\x110', '\x111', '\a', '\x31', '\x2', '\x2', 
		'\x111', '\x42', '\x3', '\x2', '\x2', '\x2', '\x112', '\x113', '\a', '-', 
		'\x2', '\x2', '\x113', '\x44', '\x3', '\x2', '\x2', '\x2', '\x114', '\x115', 
		'\a', '/', '\x2', '\x2', '\x115', '\x46', '\x3', '\x2', '\x2', '\x2', 
		'\x116', '\x117', '\a', '/', '\x2', '\x2', '\x117', '\x118', '\a', '@', 
		'\x2', '\x2', '\x118', 'H', '\x3', '\x2', '\x2', '\x2', '\x119', '\x11A', 
		'\a', '(', '\x2', '\x2', '\x11A', '\x122', '\a', '(', '\x2', '\x2', '\x11B', 
		'\x11C', '\a', '\x63', '\x2', '\x2', '\x11C', '\x11D', '\a', 'p', '\x2', 
		'\x2', '\x11D', '\x122', '\a', '\x66', '\x2', '\x2', '\x11E', '\x11F', 
		'\a', '\x43', '\x2', '\x2', '\x11F', '\x120', '\a', 'P', '\x2', '\x2', 
		'\x120', '\x122', '\a', '\x46', '\x2', '\x2', '\x121', '\x119', '\x3', 
		'\x2', '\x2', '\x2', '\x121', '\x11B', '\x3', '\x2', '\x2', '\x2', '\x121', 
		'\x11E', '\x3', '\x2', '\x2', '\x2', '\x122', 'J', '\x3', '\x2', '\x2', 
		'\x2', '\x123', '\x124', '\a', '~', '\x2', '\x2', '\x124', '\x12A', '\a', 
		'~', '\x2', '\x2', '\x125', '\x126', '\a', 'q', '\x2', '\x2', '\x126', 
		'\x12A', '\a', 't', '\x2', '\x2', '\x127', '\x128', '\a', 'Q', '\x2', 
		'\x2', '\x128', '\x12A', '\a', 'T', '\x2', '\x2', '\x129', '\x123', '\x3', 
		'\x2', '\x2', '\x2', '\x129', '\x125', '\x3', '\x2', '\x2', '\x2', '\x129', 
		'\x127', '\x3', '\x2', '\x2', '\x2', '\x12A', 'L', '\x3', '\x2', '\x2', 
		'\x2', '\x12B', '\x12D', '\t', '\x5', '\x2', '\x2', '\x12C', '\x12B', 
		'\x3', '\x2', '\x2', '\x2', '\x12D', '\x12E', '\x3', '\x2', '\x2', '\x2', 
		'\x12E', '\x12C', '\x3', '\x2', '\x2', '\x2', '\x12E', '\x12F', '\x3', 
		'\x2', '\x2', '\x2', '\x12F', 'N', '\x3', '\x2', '\x2', '\x2', '\x130', 
		'\x133', '\x5', '\x3', '\x2', '\x2', '\x131', '\x133', '\a', '\x61', '\x2', 
		'\x2', '\x132', '\x130', '\x3', '\x2', '\x2', '\x2', '\x132', '\x131', 
		'\x3', '\x2', '\x2', '\x2', '\x133', '\x134', '\x3', '\x2', '\x2', '\x2', 
		'\x134', '\x132', '\x3', '\x2', '\x2', '\x2', '\x134', '\x135', '\x3', 
		'\x2', '\x2', '\x2', '\x135', 'P', '\x3', '\x2', '\x2', '\x2', '\v', '\x2', 
		'V', 'n', '\x107', '\x121', '\x129', '\x12E', '\x132', '\x134', '\x3', 
		'\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
