//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from BetterAdvGm.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class BetterAdvGmLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		WHITESPACE=1, KEYWORD_TEXT=2, KEYWORD_STRING=3, END_STMT=4, STRING=5, 
		TRAVEL_KEYWORD=6, INCREMENT=7, CURLY_LEFT=8, CURLY_RIGHT=9, PAREN_LEFT=10, 
		PAREN_RIGHT=11, SQUARE_LEFT=12, SQUARE_RIGHT=13, KEYWORD_INPUT=14, KEYWORD_INT=15, 
		KEYWORD_IF=16, KEYWORD_ELSE=17, KEYWORD_ELSEIF=18, KEYWORD_WHILE=19, KEYWORD_FOR=20, 
		KEYWORD_LOCATION=21, KEYWORD_SETUP=22, KEYWORD_LOCATIONARRAY=23, KEYWORD_LOCATIONS=24, 
		KEYWORD_CHOICE=25, COMMA_SEPERATOR=26, BOOL_CMP_OPERATOR=27, CMP_OPERATOR=28, 
		ASSIGN_OPERATOR=29, COMPOUND_OPERATOR=30, TIMES_OPERATOR=31, DIVISION_OPERATOR=32, 
		PLUS_OPERATOR=33, MINUS_OPERATOR=34, ARROW_OPERATOR=35, AND_OPERATOR=36, 
		OR_OPERATOR=37, BOOL=38, NUM=39, VAR_NAME=40;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"LETTERS", "WHITESPACE", "KEYWORD_TEXT", "KEYWORD_STRING", "END_STMT", 
		"STRING", "TRAVEL_KEYWORD", "INCREMENT", "CURLY_LEFT", "CURLY_RIGHT", 
		"PAREN_LEFT", "PAREN_RIGHT", "SQUARE_LEFT", "SQUARE_RIGHT", "KEYWORD_INPUT", 
		"KEYWORD_INT", "KEYWORD_IF", "KEYWORD_ELSE", "KEYWORD_ELSEIF", "KEYWORD_WHILE", 
		"KEYWORD_FOR", "KEYWORD_LOCATION", "KEYWORD_SETUP", "KEYWORD_LOCATIONARRAY", 
		"KEYWORD_LOCATIONS", "KEYWORD_CHOICE", "COMMA_SEPERATOR", "BOOL_CMP_OPERATOR", 
		"CMP_OPERATOR", "ASSIGN_OPERATOR", "COMPOUND_OPERATOR", "TIMES_OPERATOR", 
		"DIVISION_OPERATOR", "PLUS_OPERATOR", "MINUS_OPERATOR", "ARROW_OPERATOR", 
		"AND_OPERATOR", "OR_OPERATOR", "BOOL", "NUM", "VAR_NAME"
	};


	public BetterAdvGmLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public BetterAdvGmLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, "'Text '", "'string '", "';'", null, "'Travel '", "'++'", 
		"'{'", "'}'", "'('", "')'", "'['", "']'", "'userInput'", "'int'", "'if'", 
		"'else'", "'else if'", "'while'", "'for'", "'Location'", "'setup'", "'LocationArray'", 
		"'Locations'", "'choice'", "','", null, null, "'='", "'+='", "'*'", "'/'", 
		"'+'", "'-'", "'->'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "WHITESPACE", "KEYWORD_TEXT", "KEYWORD_STRING", "END_STMT", "STRING", 
		"TRAVEL_KEYWORD", "INCREMENT", "CURLY_LEFT", "CURLY_RIGHT", "PAREN_LEFT", 
		"PAREN_RIGHT", "SQUARE_LEFT", "SQUARE_RIGHT", "KEYWORD_INPUT", "KEYWORD_INT", 
		"KEYWORD_IF", "KEYWORD_ELSE", "KEYWORD_ELSEIF", "KEYWORD_WHILE", "KEYWORD_FOR", 
		"KEYWORD_LOCATION", "KEYWORD_SETUP", "KEYWORD_LOCATIONARRAY", "KEYWORD_LOCATIONS", 
		"KEYWORD_CHOICE", "COMMA_SEPERATOR", "BOOL_CMP_OPERATOR", "CMP_OPERATOR", 
		"ASSIGN_OPERATOR", "COMPOUND_OPERATOR", "TIMES_OPERATOR", "DIVISION_OPERATOR", 
		"PLUS_OPERATOR", "MINUS_OPERATOR", "ARROW_OPERATOR", "AND_OPERATOR", "OR_OPERATOR", 
		"BOOL", "NUM", "VAR_NAME"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "BetterAdvGm.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static BetterAdvGmLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '*', '\x14A', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x4', '&', 
		'\t', '&', '\x4', '\'', '\t', '\'', '\x4', '(', '\t', '(', '\x4', ')', 
		'\t', ')', '\x4', '*', '\t', '*', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', 
		'\x6', '\x3', 'Y', '\n', '\x3', '\r', '\x3', '\xE', '\x3', 'Z', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\a', '\a', 
		'q', '\n', '\a', '\f', '\a', '\xE', '\a', 't', '\v', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', 
		'\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', 
		'\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', 
		'\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', 
		'\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', 
		'\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', 
		'\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', '\x1C', 
		'\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', 
		'\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', 
		'\x3', '\x1D', '\x3', '\x1D', '\x5', '\x1D', '\xF3', '\n', '\x1D', '\x3', 
		'\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', 
		'\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', 
		'\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', 
		'\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', 
		'\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', 
		'\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x5', '\x1E', '\x111', '\n', '\x1E', 
		'\x3', '\x1F', '\x3', '\x1F', '\x3', ' ', '\x3', ' ', '\x3', ' ', '\x3', 
		'!', '\x3', '!', '\x3', '\"', '\x3', '\"', '\x3', '#', '\x3', '#', '\x3', 
		'$', '\x3', '$', '\x3', '%', '\x3', '%', '\x3', '%', '\x3', '&', '\x3', 
		'&', '\x3', '&', '\x3', '&', '\x3', '&', '\x3', '&', '\x3', '&', '\x3', 
		'&', '\x5', '&', '\x12B', '\n', '&', '\x3', '\'', '\x3', '\'', '\x3', 
		'\'', '\x3', '\'', '\x3', '\'', '\x3', '\'', '\x5', '\'', '\x133', '\n', 
		'\'', '\x3', '(', '\x3', '(', '\x3', '(', '\x3', '(', '\x3', '(', '\x3', 
		'(', '\x3', '(', '\x3', '(', '\x3', '(', '\x5', '(', '\x13E', '\n', '(', 
		'\x3', ')', '\x6', ')', '\x141', '\n', ')', '\r', ')', '\xE', ')', '\x142', 
		'\x3', '*', '\x3', '*', '\x6', '*', '\x147', '\n', '*', '\r', '*', '\xE', 
		'*', '\x148', '\x2', '\x2', '+', '\x3', '\x2', '\x5', '\x3', '\a', '\x4', 
		'\t', '\x5', '\v', '\x6', '\r', '\a', '\xF', '\b', '\x11', '\t', '\x13', 
		'\n', '\x15', '\v', '\x17', '\f', '\x19', '\r', '\x1B', '\xE', '\x1D', 
		'\xF', '\x1F', '\x10', '!', '\x11', '#', '\x12', '%', '\x13', '\'', '\x14', 
		')', '\x15', '+', '\x16', '-', '\x17', '/', '\x18', '\x31', '\x19', '\x33', 
		'\x1A', '\x35', '\x1B', '\x37', '\x1C', '\x39', '\x1D', ';', '\x1E', '=', 
		'\x1F', '?', ' ', '\x41', '!', '\x43', '\"', '\x45', '#', 'G', '$', 'I', 
		'%', 'K', '&', 'M', '\'', 'O', '(', 'Q', ')', 'S', '*', '\x3', '\x2', 
		'\a', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x5', '\x2', '\v', '\f', 
		'\xF', '\xF', '\"', '\"', '\x3', '\x2', '$', '$', '\x4', '\x2', '>', '>', 
		'@', '@', '\x3', '\x2', '\x32', ';', '\x2', '\x159', '\x2', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', 
		')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', '\x3', '\x2', '\x2', 
		'\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x2', '=', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '?', '\x3', '\x2', '\x2', '\x2', '\x2', '\x41', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x43', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x45', '\x3', '\x2', '\x2', '\x2', '\x2', 'G', '\x3', '\x2', '\x2', '\x2', 
		'\x2', 'I', '\x3', '\x2', '\x2', '\x2', '\x2', 'K', '\x3', '\x2', '\x2', 
		'\x2', '\x2', 'M', '\x3', '\x2', '\x2', '\x2', '\x2', 'O', '\x3', '\x2', 
		'\x2', '\x2', '\x2', 'Q', '\x3', '\x2', '\x2', '\x2', '\x2', 'S', '\x3', 
		'\x2', '\x2', '\x2', '\x3', 'U', '\x3', '\x2', '\x2', '\x2', '\x5', 'X', 
		'\x3', '\x2', '\x2', '\x2', '\a', '^', '\x3', '\x2', '\x2', '\x2', '\t', 
		'\x64', '\x3', '\x2', '\x2', '\x2', '\v', 'l', '\x3', '\x2', '\x2', '\x2', 
		'\r', 'n', '\x3', '\x2', '\x2', '\x2', '\xF', 'w', '\x3', '\x2', '\x2', 
		'\x2', '\x11', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x13', '\x82', '\x3', 
		'\x2', '\x2', '\x2', '\x15', '\x84', '\x3', '\x2', '\x2', '\x2', '\x17', 
		'\x86', '\x3', '\x2', '\x2', '\x2', '\x19', '\x88', '\x3', '\x2', '\x2', 
		'\x2', '\x1B', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x8C', '\x3', 
		'\x2', '\x2', '\x2', '\x1F', '\x8E', '\x3', '\x2', '\x2', '\x2', '!', 
		'\x98', '\x3', '\x2', '\x2', '\x2', '#', '\x9C', '\x3', '\x2', '\x2', 
		'\x2', '%', '\x9F', '\x3', '\x2', '\x2', '\x2', '\'', '\xA4', '\x3', '\x2', 
		'\x2', '\x2', ')', '\xAC', '\x3', '\x2', '\x2', '\x2', '+', '\xB2', '\x3', 
		'\x2', '\x2', '\x2', '-', '\xB6', '\x3', '\x2', '\x2', '\x2', '/', '\xBF', 
		'\x3', '\x2', '\x2', '\x2', '\x31', '\xC5', '\x3', '\x2', '\x2', '\x2', 
		'\x33', '\xD3', '\x3', '\x2', '\x2', '\x2', '\x35', '\xDD', '\x3', '\x2', 
		'\x2', '\x2', '\x37', '\xE4', '\x3', '\x2', '\x2', '\x2', '\x39', '\xF2', 
		'\x3', '\x2', '\x2', '\x2', ';', '\x110', '\x3', '\x2', '\x2', '\x2', 
		'=', '\x112', '\x3', '\x2', '\x2', '\x2', '?', '\x114', '\x3', '\x2', 
		'\x2', '\x2', '\x41', '\x117', '\x3', '\x2', '\x2', '\x2', '\x43', '\x119', 
		'\x3', '\x2', '\x2', '\x2', '\x45', '\x11B', '\x3', '\x2', '\x2', '\x2', 
		'G', '\x11D', '\x3', '\x2', '\x2', '\x2', 'I', '\x11F', '\x3', '\x2', 
		'\x2', '\x2', 'K', '\x12A', '\x3', '\x2', '\x2', '\x2', 'M', '\x132', 
		'\x3', '\x2', '\x2', '\x2', 'O', '\x13D', '\x3', '\x2', '\x2', '\x2', 
		'Q', '\x140', '\x3', '\x2', '\x2', '\x2', 'S', '\x146', '\x3', '\x2', 
		'\x2', '\x2', 'U', 'V', '\t', '\x2', '\x2', '\x2', 'V', '\x4', '\x3', 
		'\x2', '\x2', '\x2', 'W', 'Y', '\t', '\x3', '\x2', '\x2', 'X', 'W', '\x3', 
		'\x2', '\x2', '\x2', 'Y', 'Z', '\x3', '\x2', '\x2', '\x2', 'Z', 'X', '\x3', 
		'\x2', '\x2', '\x2', 'Z', '[', '\x3', '\x2', '\x2', '\x2', '[', '\\', 
		'\x3', '\x2', '\x2', '\x2', '\\', ']', '\b', '\x3', '\x2', '\x2', ']', 
		'\x6', '\x3', '\x2', '\x2', '\x2', '^', '_', '\a', 'V', '\x2', '\x2', 
		'_', '`', '\a', 'g', '\x2', '\x2', '`', '\x61', '\a', 'z', '\x2', '\x2', 
		'\x61', '\x62', '\a', 'v', '\x2', '\x2', '\x62', '\x63', '\a', '\"', '\x2', 
		'\x2', '\x63', '\b', '\x3', '\x2', '\x2', '\x2', '\x64', '\x65', '\a', 
		'u', '\x2', '\x2', '\x65', '\x66', '\a', 'v', '\x2', '\x2', '\x66', 'g', 
		'\a', 't', '\x2', '\x2', 'g', 'h', '\a', 'k', '\x2', '\x2', 'h', 'i', 
		'\a', 'p', '\x2', '\x2', 'i', 'j', '\a', 'i', '\x2', '\x2', 'j', 'k', 
		'\a', '\"', '\x2', '\x2', 'k', '\n', '\x3', '\x2', '\x2', '\x2', 'l', 
		'm', '\a', '=', '\x2', '\x2', 'm', '\f', '\x3', '\x2', '\x2', '\x2', 'n', 
		'r', '\a', '$', '\x2', '\x2', 'o', 'q', '\n', '\x4', '\x2', '\x2', 'p', 
		'o', '\x3', '\x2', '\x2', '\x2', 'q', 't', '\x3', '\x2', '\x2', '\x2', 
		'r', 'p', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\x3', '\x2', '\x2', '\x2', 
		's', 'u', '\x3', '\x2', '\x2', '\x2', 't', 'r', '\x3', '\x2', '\x2', '\x2', 
		'u', 'v', '\a', '$', '\x2', '\x2', 'v', '\xE', '\x3', '\x2', '\x2', '\x2', 
		'w', 'x', '\a', 'V', '\x2', '\x2', 'x', 'y', '\a', 't', '\x2', '\x2', 
		'y', 'z', '\a', '\x63', '\x2', '\x2', 'z', '{', '\a', 'x', '\x2', '\x2', 
		'{', '|', '\a', 'g', '\x2', '\x2', '|', '}', '\a', 'n', '\x2', '\x2', 
		'}', '~', '\a', '\"', '\x2', '\x2', '~', '\x10', '\x3', '\x2', '\x2', 
		'\x2', '\x7F', '\x80', '\a', '-', '\x2', '\x2', '\x80', '\x81', '\a', 
		'-', '\x2', '\x2', '\x81', '\x12', '\x3', '\x2', '\x2', '\x2', '\x82', 
		'\x83', '\a', '}', '\x2', '\x2', '\x83', '\x14', '\x3', '\x2', '\x2', 
		'\x2', '\x84', '\x85', '\a', '\x7F', '\x2', '\x2', '\x85', '\x16', '\x3', 
		'\x2', '\x2', '\x2', '\x86', '\x87', '\a', '*', '\x2', '\x2', '\x87', 
		'\x18', '\x3', '\x2', '\x2', '\x2', '\x88', '\x89', '\a', '+', '\x2', 
		'\x2', '\x89', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\a', 
		']', '\x2', '\x2', '\x8B', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x8C', 
		'\x8D', '\a', '_', '\x2', '\x2', '\x8D', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', '\x8E', '\x8F', '\a', 'w', '\x2', '\x2', '\x8F', '\x90', '\a', 
		'u', '\x2', '\x2', '\x90', '\x91', '\a', 'g', '\x2', '\x2', '\x91', '\x92', 
		'\a', 't', '\x2', '\x2', '\x92', '\x93', '\a', 'K', '\x2', '\x2', '\x93', 
		'\x94', '\a', 'p', '\x2', '\x2', '\x94', '\x95', '\a', 'r', '\x2', '\x2', 
		'\x95', '\x96', '\a', 'w', '\x2', '\x2', '\x96', '\x97', '\a', 'v', '\x2', 
		'\x2', '\x97', ' ', '\x3', '\x2', '\x2', '\x2', '\x98', '\x99', '\a', 
		'k', '\x2', '\x2', '\x99', '\x9A', '\a', 'p', '\x2', '\x2', '\x9A', '\x9B', 
		'\a', 'v', '\x2', '\x2', '\x9B', '\"', '\x3', '\x2', '\x2', '\x2', '\x9C', 
		'\x9D', '\a', 'k', '\x2', '\x2', '\x9D', '\x9E', '\a', 'h', '\x2', '\x2', 
		'\x9E', '$', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', '\a', 'g', '\x2', 
		'\x2', '\xA0', '\xA1', '\a', 'n', '\x2', '\x2', '\xA1', '\xA2', '\a', 
		'u', '\x2', '\x2', '\xA2', '\xA3', '\a', 'g', '\x2', '\x2', '\xA3', '&', 
		'\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', '\a', 'g', '\x2', '\x2', '\xA5', 
		'\xA6', '\a', 'n', '\x2', '\x2', '\xA6', '\xA7', '\a', 'u', '\x2', '\x2', 
		'\xA7', '\xA8', '\a', 'g', '\x2', '\x2', '\xA8', '\xA9', '\a', '\"', '\x2', 
		'\x2', '\xA9', '\xAA', '\a', 'k', '\x2', '\x2', '\xAA', '\xAB', '\a', 
		'h', '\x2', '\x2', '\xAB', '(', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAD', 
		'\a', 'y', '\x2', '\x2', '\xAD', '\xAE', '\a', 'j', '\x2', '\x2', '\xAE', 
		'\xAF', '\a', 'k', '\x2', '\x2', '\xAF', '\xB0', '\a', 'n', '\x2', '\x2', 
		'\xB0', '\xB1', '\a', 'g', '\x2', '\x2', '\xB1', '*', '\x3', '\x2', '\x2', 
		'\x2', '\xB2', '\xB3', '\a', 'h', '\x2', '\x2', '\xB3', '\xB4', '\a', 
		'q', '\x2', '\x2', '\xB4', '\xB5', '\a', 't', '\x2', '\x2', '\xB5', ',', 
		'\x3', '\x2', '\x2', '\x2', '\xB6', '\xB7', '\a', 'N', '\x2', '\x2', '\xB7', 
		'\xB8', '\a', 'q', '\x2', '\x2', '\xB8', '\xB9', '\a', '\x65', '\x2', 
		'\x2', '\xB9', '\xBA', '\a', '\x63', '\x2', '\x2', '\xBA', '\xBB', '\a', 
		'v', '\x2', '\x2', '\xBB', '\xBC', '\a', 'k', '\x2', '\x2', '\xBC', '\xBD', 
		'\a', 'q', '\x2', '\x2', '\xBD', '\xBE', '\a', 'p', '\x2', '\x2', '\xBE', 
		'.', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xC0', '\a', 'u', '\x2', '\x2', 
		'\xC0', '\xC1', '\a', 'g', '\x2', '\x2', '\xC1', '\xC2', '\a', 'v', '\x2', 
		'\x2', '\xC2', '\xC3', '\a', 'w', '\x2', '\x2', '\xC3', '\xC4', '\a', 
		'r', '\x2', '\x2', '\xC4', '\x30', '\x3', '\x2', '\x2', '\x2', '\xC5', 
		'\xC6', '\a', 'N', '\x2', '\x2', '\xC6', '\xC7', '\a', 'q', '\x2', '\x2', 
		'\xC7', '\xC8', '\a', '\x65', '\x2', '\x2', '\xC8', '\xC9', '\a', '\x63', 
		'\x2', '\x2', '\xC9', '\xCA', '\a', 'v', '\x2', '\x2', '\xCA', '\xCB', 
		'\a', 'k', '\x2', '\x2', '\xCB', '\xCC', '\a', 'q', '\x2', '\x2', '\xCC', 
		'\xCD', '\a', 'p', '\x2', '\x2', '\xCD', '\xCE', '\a', '\x43', '\x2', 
		'\x2', '\xCE', '\xCF', '\a', 't', '\x2', '\x2', '\xCF', '\xD0', '\a', 
		't', '\x2', '\x2', '\xD0', '\xD1', '\a', '\x63', '\x2', '\x2', '\xD1', 
		'\xD2', '\a', '{', '\x2', '\x2', '\xD2', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\xD3', '\xD4', '\a', 'N', '\x2', '\x2', '\xD4', '\xD5', '\a', 
		'q', '\x2', '\x2', '\xD5', '\xD6', '\a', '\x65', '\x2', '\x2', '\xD6', 
		'\xD7', '\a', '\x63', '\x2', '\x2', '\xD7', '\xD8', '\a', 'v', '\x2', 
		'\x2', '\xD8', '\xD9', '\a', 'k', '\x2', '\x2', '\xD9', '\xDA', '\a', 
		'q', '\x2', '\x2', '\xDA', '\xDB', '\a', 'p', '\x2', '\x2', '\xDB', '\xDC', 
		'\a', 'u', '\x2', '\x2', '\xDC', '\x34', '\x3', '\x2', '\x2', '\x2', '\xDD', 
		'\xDE', '\a', '\x65', '\x2', '\x2', '\xDE', '\xDF', '\a', 'j', '\x2', 
		'\x2', '\xDF', '\xE0', '\a', 'q', '\x2', '\x2', '\xE0', '\xE1', '\a', 
		'k', '\x2', '\x2', '\xE1', '\xE2', '\a', '\x65', '\x2', '\x2', '\xE2', 
		'\xE3', '\a', 'g', '\x2', '\x2', '\xE3', '\x36', '\x3', '\x2', '\x2', 
		'\x2', '\xE4', '\xE5', '\a', '.', '\x2', '\x2', '\xE5', '\x38', '\x3', 
		'\x2', '\x2', '\x2', '\xE6', '\xE7', '\a', '?', '\x2', '\x2', '\xE7', 
		'\xF3', '\a', '?', '\x2', '\x2', '\xE8', '\xE9', '\a', 'k', '\x2', '\x2', 
		'\xE9', '\xF3', '\a', 'u', '\x2', '\x2', '\xEA', '\xEB', '\a', '#', '\x2', 
		'\x2', '\xEB', '\xF3', '\a', '?', '\x2', '\x2', '\xEC', '\xED', '\a', 
		'k', '\x2', '\x2', '\xED', '\xEE', '\a', 'u', '\x2', '\x2', '\xEE', '\xEF', 
		'\a', '\"', '\x2', '\x2', '\xEF', '\xF0', '\a', 'p', '\x2', '\x2', '\xF0', 
		'\xF1', '\a', 'q', '\x2', '\x2', '\xF1', '\xF3', '\a', 'v', '\x2', '\x2', 
		'\xF2', '\xE6', '\x3', '\x2', '\x2', '\x2', '\xF2', '\xE8', '\x3', '\x2', 
		'\x2', '\x2', '\xF2', '\xEA', '\x3', '\x2', '\x2', '\x2', '\xF2', '\xEC', 
		'\x3', '\x2', '\x2', '\x2', '\xF3', ':', '\x3', '\x2', '\x2', '\x2', '\xF4', 
		'\xF5', '\a', 'i', '\x2', '\x2', '\xF5', '\xF6', '\a', 't', '\x2', '\x2', 
		'\xF6', '\xF7', '\a', 'g', '\x2', '\x2', '\xF7', '\xF8', '\a', '\x63', 
		'\x2', '\x2', '\xF8', '\xF9', '\a', 'v', '\x2', '\x2', '\xF9', '\xFA', 
		'\a', 'g', '\x2', '\x2', '\xFA', '\xFB', '\a', 't', '\x2', '\x2', '\xFB', 
		'\xFC', '\a', '\"', '\x2', '\x2', '\xFC', '\xFD', '\a', 'v', '\x2', '\x2', 
		'\xFD', '\xFE', '\a', 'j', '\x2', '\x2', '\xFE', '\xFF', '\a', '\x63', 
		'\x2', '\x2', '\xFF', '\x111', '\a', 'p', '\x2', '\x2', '\x100', '\x101', 
		'\a', 'n', '\x2', '\x2', '\x101', '\x102', '\a', 'g', '\x2', '\x2', '\x102', 
		'\x103', '\a', 'u', '\x2', '\x2', '\x103', '\x104', '\a', 'u', '\x2', 
		'\x2', '\x104', '\x105', '\a', 'g', '\x2', '\x2', '\x105', '\x106', '\a', 
		't', '\x2', '\x2', '\x106', '\x107', '\a', '\"', '\x2', '\x2', '\x107', 
		'\x108', '\a', 'v', '\x2', '\x2', '\x108', '\x109', '\a', 'j', '\x2', 
		'\x2', '\x109', '\x10A', '\a', '\x63', '\x2', '\x2', '\x10A', '\x111', 
		'\a', 'p', '\x2', '\x2', '\x10B', '\x111', '\t', '\x5', '\x2', '\x2', 
		'\x10C', '\x10D', '\a', '>', '\x2', '\x2', '\x10D', '\x111', '\a', '?', 
		'\x2', '\x2', '\x10E', '\x10F', '\a', '@', '\x2', '\x2', '\x10F', '\x111', 
		'\a', '?', '\x2', '\x2', '\x110', '\xF4', '\x3', '\x2', '\x2', '\x2', 
		'\x110', '\x100', '\x3', '\x2', '\x2', '\x2', '\x110', '\x10B', '\x3', 
		'\x2', '\x2', '\x2', '\x110', '\x10C', '\x3', '\x2', '\x2', '\x2', '\x110', 
		'\x10E', '\x3', '\x2', '\x2', '\x2', '\x111', '<', '\x3', '\x2', '\x2', 
		'\x2', '\x112', '\x113', '\a', '?', '\x2', '\x2', '\x113', '>', '\x3', 
		'\x2', '\x2', '\x2', '\x114', '\x115', '\a', '-', '\x2', '\x2', '\x115', 
		'\x116', '\a', '?', '\x2', '\x2', '\x116', '@', '\x3', '\x2', '\x2', '\x2', 
		'\x117', '\x118', '\a', ',', '\x2', '\x2', '\x118', '\x42', '\x3', '\x2', 
		'\x2', '\x2', '\x119', '\x11A', '\a', '\x31', '\x2', '\x2', '\x11A', '\x44', 
		'\x3', '\x2', '\x2', '\x2', '\x11B', '\x11C', '\a', '-', '\x2', '\x2', 
		'\x11C', '\x46', '\x3', '\x2', '\x2', '\x2', '\x11D', '\x11E', '\a', '/', 
		'\x2', '\x2', '\x11E', 'H', '\x3', '\x2', '\x2', '\x2', '\x11F', '\x120', 
		'\a', '/', '\x2', '\x2', '\x120', '\x121', '\a', '@', '\x2', '\x2', '\x121', 
		'J', '\x3', '\x2', '\x2', '\x2', '\x122', '\x123', '\a', '(', '\x2', '\x2', 
		'\x123', '\x12B', '\a', '(', '\x2', '\x2', '\x124', '\x125', '\a', '\x63', 
		'\x2', '\x2', '\x125', '\x126', '\a', 'p', '\x2', '\x2', '\x126', '\x12B', 
		'\a', '\x66', '\x2', '\x2', '\x127', '\x128', '\a', '\x43', '\x2', '\x2', 
		'\x128', '\x129', '\a', 'P', '\x2', '\x2', '\x129', '\x12B', '\a', '\x46', 
		'\x2', '\x2', '\x12A', '\x122', '\x3', '\x2', '\x2', '\x2', '\x12A', '\x124', 
		'\x3', '\x2', '\x2', '\x2', '\x12A', '\x127', '\x3', '\x2', '\x2', '\x2', 
		'\x12B', 'L', '\x3', '\x2', '\x2', '\x2', '\x12C', '\x12D', '\a', '~', 
		'\x2', '\x2', '\x12D', '\x133', '\a', '~', '\x2', '\x2', '\x12E', '\x12F', 
		'\a', 'q', '\x2', '\x2', '\x12F', '\x133', '\a', 't', '\x2', '\x2', '\x130', 
		'\x131', '\a', 'Q', '\x2', '\x2', '\x131', '\x133', '\a', 'T', '\x2', 
		'\x2', '\x132', '\x12C', '\x3', '\x2', '\x2', '\x2', '\x132', '\x12E', 
		'\x3', '\x2', '\x2', '\x2', '\x132', '\x130', '\x3', '\x2', '\x2', '\x2', 
		'\x133', 'N', '\x3', '\x2', '\x2', '\x2', '\x134', '\x135', '\a', 'v', 
		'\x2', '\x2', '\x135', '\x136', '\a', 't', '\x2', '\x2', '\x136', '\x137', 
		'\a', 'w', '\x2', '\x2', '\x137', '\x13E', '\a', 'g', '\x2', '\x2', '\x138', 
		'\x139', '\a', 'h', '\x2', '\x2', '\x139', '\x13A', '\a', '\x63', '\x2', 
		'\x2', '\x13A', '\x13B', '\a', 'n', '\x2', '\x2', '\x13B', '\x13C', '\a', 
		'u', '\x2', '\x2', '\x13C', '\x13E', '\a', 'g', '\x2', '\x2', '\x13D', 
		'\x134', '\x3', '\x2', '\x2', '\x2', '\x13D', '\x138', '\x3', '\x2', '\x2', 
		'\x2', '\x13E', 'P', '\x3', '\x2', '\x2', '\x2', '\x13F', '\x141', '\t', 
		'\x6', '\x2', '\x2', '\x140', '\x13F', '\x3', '\x2', '\x2', '\x2', '\x141', 
		'\x142', '\x3', '\x2', '\x2', '\x2', '\x142', '\x140', '\x3', '\x2', '\x2', 
		'\x2', '\x142', '\x143', '\x3', '\x2', '\x2', '\x2', '\x143', 'R', '\x3', 
		'\x2', '\x2', '\x2', '\x144', '\x147', '\x5', '\x3', '\x2', '\x2', '\x145', 
		'\x147', '\a', '\x61', '\x2', '\x2', '\x146', '\x144', '\x3', '\x2', '\x2', 
		'\x2', '\x146', '\x145', '\x3', '\x2', '\x2', '\x2', '\x147', '\x148', 
		'\x3', '\x2', '\x2', '\x2', '\x148', '\x146', '\x3', '\x2', '\x2', '\x2', 
		'\x148', '\x149', '\x3', '\x2', '\x2', '\x2', '\x149', 'T', '\x3', '\x2', 
		'\x2', '\x2', '\r', '\x2', 'Z', 'r', '\xF2', '\x110', '\x12A', '\x132', 
		'\x13D', '\x142', '\x146', '\x148', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
