//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from BetterAdvGm.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IBetterAdvGmListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class BetterAdvGmBaseListener : IBetterAdvGmListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] BetterAdvGmParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] BetterAdvGmParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.buffernode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBuffernode([NotNull] BetterAdvGmParser.BuffernodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.buffernode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBuffernode([NotNull] BetterAdvGmParser.BuffernodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.setup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetup([NotNull] BetterAdvGmParser.SetupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.setup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetup([NotNull] BetterAdvGmParser.SetupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.locationsetup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocationsetup([NotNull] BetterAdvGmParser.LocationsetupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.locationsetup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocationsetup([NotNull] BetterAdvGmParser.LocationsetupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.locationmapping"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocationmapping([NotNull] BetterAdvGmParser.LocationmappingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.locationmapping"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocationmapping([NotNull] BetterAdvGmParser.LocationmappingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.playersetup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlayersetup([NotNull] BetterAdvGmParser.PlayersetupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.playersetup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlayersetup([NotNull] BetterAdvGmParser.PlayersetupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.inBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInBlock([NotNull] BetterAdvGmParser.InBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.inBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInBlock([NotNull] BetterAdvGmParser.InBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] BetterAdvGmParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] BetterAdvGmParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] BetterAdvGmParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] BetterAdvGmParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssign([NotNull] BetterAdvGmParser.AssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssign([NotNull] BetterAdvGmParser.AssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] BetterAdvGmParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] BetterAdvGmParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.text_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterText_statement([NotNull] BetterAdvGmParser.Text_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.text_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitText_statement([NotNull] BetterAdvGmParser.Text_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.input_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInput_statement([NotNull] BetterAdvGmParser.Input_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.input_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInput_statement([NotNull] BetterAdvGmParser.Input_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.if_chain_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_chain_statement([NotNull] BetterAdvGmParser.If_chain_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.if_chain_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_chain_statement([NotNull] BetterAdvGmParser.If_chain_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_statement([NotNull] BetterAdvGmParser.If_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_statement([NotNull] BetterAdvGmParser.If_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.else_if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse_if_statement([NotNull] BetterAdvGmParser.Else_if_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.else_if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse_if_statement([NotNull] BetterAdvGmParser.Else_if_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.else_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse_statement([NotNull] BetterAdvGmParser.Else_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.else_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse_statement([NotNull] BetterAdvGmParser.Else_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.travel_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTravel_statement([NotNull] BetterAdvGmParser.Travel_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.travel_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTravel_statement([NotNull] BetterAdvGmParser.Travel_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.choice_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChoice_statement([NotNull] BetterAdvGmParser.Choice_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.choice_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChoice_statement([NotNull] BetterAdvGmParser.Choice_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.option_statment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOption_statment([NotNull] BetterAdvGmParser.Option_statmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.option_statment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOption_statment([NotNull] BetterAdvGmParser.Option_statmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.while_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhile_statement([NotNull] BetterAdvGmParser.While_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.while_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhile_statement([NotNull] BetterAdvGmParser.While_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.int_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInt_assign([NotNull] BetterAdvGmParser.Int_assignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.int_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInt_assign([NotNull] BetterAdvGmParser.Int_assignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.string_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_assign([NotNull] BetterAdvGmParser.String_assignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.string_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_assign([NotNull] BetterAdvGmParser.String_assignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.input_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInput_assign([NotNull] BetterAdvGmParser.Input_assignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.input_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInput_assign([NotNull] BetterAdvGmParser.Input_assignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.location_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocation_assign([NotNull] BetterAdvGmParser.Location_assignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.location_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocation_assign([NotNull] BetterAdvGmParser.Location_assignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.int_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInt_declaration([NotNull] BetterAdvGmParser.Int_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.int_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInt_declaration([NotNull] BetterAdvGmParser.Int_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.string_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_declaration([NotNull] BetterAdvGmParser.String_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.string_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_declaration([NotNull] BetterAdvGmParser.String_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.location_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocation_declaration([NotNull] BetterAdvGmParser.Location_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.location_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocation_declaration([NotNull] BetterAdvGmParser.Location_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicate([NotNull] BetterAdvGmParser.PredicateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicate([NotNull] BetterAdvGmParser.PredicateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] BetterAdvGmParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] BetterAdvGmParser.VariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.string_obj"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_obj([NotNull] BetterAdvGmParser.String_objContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.string_obj"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_obj([NotNull] BetterAdvGmParser.String_objContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BetterAdvGmParser.bool_obj"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool_obj([NotNull] BetterAdvGmParser.Bool_objContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BetterAdvGmParser.bool_obj"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool_obj([NotNull] BetterAdvGmParser.Bool_objContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
