//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SWAE.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SWAEParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface ISWAEVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] SWAEParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.buffernode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBuffernode([NotNull] SWAEParser.BuffernodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.setup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetup([NotNull] SWAEParser.SetupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.locationsetup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocationsetup([NotNull] SWAEParser.LocationsetupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.locationmapping"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocationmapping([NotNull] SWAEParser.LocationmappingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.playersetup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlayersetup([NotNull] SWAEParser.PlayersetupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.inBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInBlock([NotNull] SWAEParser.InBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] SWAEParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] SWAEParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssign([NotNull] SWAEParser.AssignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] SWAEParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.text_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitText_statement([NotNull] SWAEParser.Text_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.input_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInput_statement([NotNull] SWAEParser.Input_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.if_chain_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_chain_statement([NotNull] SWAEParser.If_chain_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_statement([NotNull] SWAEParser.If_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.else_if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse_if_statement([NotNull] SWAEParser.Else_if_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.else_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse_statement([NotNull] SWAEParser.Else_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.travel_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTravel_statement([NotNull] SWAEParser.Travel_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.choice_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChoice_statement([NotNull] SWAEParser.Choice_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.option_statment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOption_statment([NotNull] SWAEParser.Option_statmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.while_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile_statement([NotNull] SWAEParser.While_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.int_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt_assign([NotNull] SWAEParser.Int_assignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.string_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_assign([NotNull] SWAEParser.String_assignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.input_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInput_assign([NotNull] SWAEParser.Input_assignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.location_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocation_assign([NotNull] SWAEParser.Location_assignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.bool_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool_assign([NotNull] SWAEParser.Bool_assignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.int_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt_declaration([NotNull] SWAEParser.Int_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.string_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_declaration([NotNull] SWAEParser.String_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.location_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocation_declaration([NotNull] SWAEParser.Location_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.bool_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool_declaration([NotNull] SWAEParser.Bool_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredicate([NotNull] SWAEParser.PredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.random"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRandom([NotNull] SWAEParser.RandomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] SWAEParser.VariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.string_obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_obj([NotNull] SWAEParser.String_objContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.bool_obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool_obj([NotNull] SWAEParser.Bool_objContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SWAEParser.dot_notaion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDot_notaion([NotNull] SWAEParser.Dot_notaionContext context);
}
