//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SWAE.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SWAEParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface ISWAEListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] SWAEParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] SWAEParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.buffernode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBuffernode([NotNull] SWAEParser.BuffernodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.buffernode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBuffernode([NotNull] SWAEParser.BuffernodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.setup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetup([NotNull] SWAEParser.SetupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.setup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetup([NotNull] SWAEParser.SetupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.locationsetup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocationsetup([NotNull] SWAEParser.LocationsetupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.locationsetup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocationsetup([NotNull] SWAEParser.LocationsetupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.locationmapping"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocationmapping([NotNull] SWAEParser.LocationmappingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.locationmapping"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocationmapping([NotNull] SWAEParser.LocationmappingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.playersetup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlayersetup([NotNull] SWAEParser.PlayersetupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.playersetup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlayersetup([NotNull] SWAEParser.PlayersetupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.inBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInBlock([NotNull] SWAEParser.InBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.inBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInBlock([NotNull] SWAEParser.InBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] SWAEParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] SWAEParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] SWAEParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] SWAEParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssign([NotNull] SWAEParser.AssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssign([NotNull] SWAEParser.AssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] SWAEParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] SWAEParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.text_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterText_statement([NotNull] SWAEParser.Text_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.text_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitText_statement([NotNull] SWAEParser.Text_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.input_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInput_statement([NotNull] SWAEParser.Input_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.input_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInput_statement([NotNull] SWAEParser.Input_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.if_chain_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_chain_statement([NotNull] SWAEParser.If_chain_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.if_chain_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_chain_statement([NotNull] SWAEParser.If_chain_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_statement([NotNull] SWAEParser.If_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_statement([NotNull] SWAEParser.If_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.else_if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElse_if_statement([NotNull] SWAEParser.Else_if_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.else_if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElse_if_statement([NotNull] SWAEParser.Else_if_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.else_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElse_statement([NotNull] SWAEParser.Else_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.else_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElse_statement([NotNull] SWAEParser.Else_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.travel_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTravel_statement([NotNull] SWAEParser.Travel_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.travel_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTravel_statement([NotNull] SWAEParser.Travel_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.choice_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChoice_statement([NotNull] SWAEParser.Choice_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.choice_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChoice_statement([NotNull] SWAEParser.Choice_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.option_statment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOption_statment([NotNull] SWAEParser.Option_statmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.option_statment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOption_statment([NotNull] SWAEParser.Option_statmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.while_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile_statement([NotNull] SWAEParser.While_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.while_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile_statement([NotNull] SWAEParser.While_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.int_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInt_assign([NotNull] SWAEParser.Int_assignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.int_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInt_assign([NotNull] SWAEParser.Int_assignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.string_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_assign([NotNull] SWAEParser.String_assignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.string_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_assign([NotNull] SWAEParser.String_assignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.input_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInput_assign([NotNull] SWAEParser.Input_assignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.input_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInput_assign([NotNull] SWAEParser.Input_assignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.location_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocation_assign([NotNull] SWAEParser.Location_assignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.location_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocation_assign([NotNull] SWAEParser.Location_assignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.bool_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool_assign([NotNull] SWAEParser.Bool_assignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.bool_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool_assign([NotNull] SWAEParser.Bool_assignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.int_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInt_declaration([NotNull] SWAEParser.Int_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.int_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInt_declaration([NotNull] SWAEParser.Int_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.string_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_declaration([NotNull] SWAEParser.String_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.string_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_declaration([NotNull] SWAEParser.String_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.location_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocation_declaration([NotNull] SWAEParser.Location_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.location_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocation_declaration([NotNull] SWAEParser.Location_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.bool_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool_declaration([NotNull] SWAEParser.Bool_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.bool_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool_declaration([NotNull] SWAEParser.Bool_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPredicate([NotNull] SWAEParser.PredicateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPredicate([NotNull] SWAEParser.PredicateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.random"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRandom([NotNull] SWAEParser.RandomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.random"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRandom([NotNull] SWAEParser.RandomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable([NotNull] SWAEParser.VariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable([NotNull] SWAEParser.VariableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.string_obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_obj([NotNull] SWAEParser.String_objContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.string_obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_obj([NotNull] SWAEParser.String_objContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.bool_obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool_obj([NotNull] SWAEParser.Bool_objContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.bool_obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool_obj([NotNull] SWAEParser.Bool_objContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.dot_notaion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDot_notaion([NotNull] SWAEParser.Dot_notaionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.dot_notaion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDot_notaion([NotNull] SWAEParser.Dot_notaionContext context);
}
