//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SWAE.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISWAEListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class SWAEBaseListener : ISWAEListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] SWAEParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] SWAEParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.buffernode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBuffernode([NotNull] SWAEParser.BuffernodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.buffernode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBuffernode([NotNull] SWAEParser.BuffernodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.setup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetup([NotNull] SWAEParser.SetupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.setup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetup([NotNull] SWAEParser.SetupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.locationsetup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocationsetup([NotNull] SWAEParser.LocationsetupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.locationsetup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocationsetup([NotNull] SWAEParser.LocationsetupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.locationmapping"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocationmapping([NotNull] SWAEParser.LocationmappingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.locationmapping"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocationmapping([NotNull] SWAEParser.LocationmappingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.playersetup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlayersetup([NotNull] SWAEParser.PlayersetupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.playersetup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlayersetup([NotNull] SWAEParser.PlayersetupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.inBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInBlock([NotNull] SWAEParser.InBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.inBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInBlock([NotNull] SWAEParser.InBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] SWAEParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] SWAEParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] SWAEParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] SWAEParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssign([NotNull] SWAEParser.AssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssign([NotNull] SWAEParser.AssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] SWAEParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] SWAEParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.text_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterText_statement([NotNull] SWAEParser.Text_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.text_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitText_statement([NotNull] SWAEParser.Text_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.input_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInput_statement([NotNull] SWAEParser.Input_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.input_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInput_statement([NotNull] SWAEParser.Input_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.if_chain_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_chain_statement([NotNull] SWAEParser.If_chain_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.if_chain_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_chain_statement([NotNull] SWAEParser.If_chain_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_statement([NotNull] SWAEParser.If_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_statement([NotNull] SWAEParser.If_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.else_if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse_if_statement([NotNull] SWAEParser.Else_if_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.else_if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse_if_statement([NotNull] SWAEParser.Else_if_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.else_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse_statement([NotNull] SWAEParser.Else_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.else_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse_statement([NotNull] SWAEParser.Else_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.travel_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTravel_statement([NotNull] SWAEParser.Travel_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.travel_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTravel_statement([NotNull] SWAEParser.Travel_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.choice_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChoice_statement([NotNull] SWAEParser.Choice_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.choice_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChoice_statement([NotNull] SWAEParser.Choice_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.option_statment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOption_statment([NotNull] SWAEParser.Option_statmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.option_statment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOption_statment([NotNull] SWAEParser.Option_statmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.while_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhile_statement([NotNull] SWAEParser.While_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.while_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhile_statement([NotNull] SWAEParser.While_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.anonymous_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnonymous_assign([NotNull] SWAEParser.Anonymous_assignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.anonymous_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnonymous_assign([NotNull] SWAEParser.Anonymous_assignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.int_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInt_assign([NotNull] SWAEParser.Int_assignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.int_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInt_assign([NotNull] SWAEParser.Int_assignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.string_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_assign([NotNull] SWAEParser.String_assignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.string_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_assign([NotNull] SWAEParser.String_assignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.input_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInput_assign([NotNull] SWAEParser.Input_assignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.input_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInput_assign([NotNull] SWAEParser.Input_assignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.location_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocation_assign([NotNull] SWAEParser.Location_assignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.location_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocation_assign([NotNull] SWAEParser.Location_assignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.bool_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool_assign([NotNull] SWAEParser.Bool_assignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.bool_assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool_assign([NotNull] SWAEParser.Bool_assignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.int_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInt_declaration([NotNull] SWAEParser.Int_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.int_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInt_declaration([NotNull] SWAEParser.Int_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.string_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_declaration([NotNull] SWAEParser.String_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.string_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_declaration([NotNull] SWAEParser.String_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.location_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocation_declaration([NotNull] SWAEParser.Location_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.location_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocation_declaration([NotNull] SWAEParser.Location_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.bool_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool_declaration([NotNull] SWAEParser.Bool_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.bool_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool_declaration([NotNull] SWAEParser.Bool_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicate([NotNull] SWAEParser.PredicateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicate([NotNull] SWAEParser.PredicateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.random"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRandom([NotNull] SWAEParser.RandomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.random"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRandom([NotNull] SWAEParser.RandomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] SWAEParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] SWAEParser.VariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.string_obj"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_obj([NotNull] SWAEParser.String_objContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.string_obj"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_obj([NotNull] SWAEParser.String_objContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.bool_obj"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool_obj([NotNull] SWAEParser.Bool_objContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.bool_obj"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool_obj([NotNull] SWAEParser.Bool_objContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SWAEParser.dot_notaion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDot_notaion([NotNull] SWAEParser.Dot_notaionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SWAEParser.dot_notaion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDot_notaion([NotNull] SWAEParser.Dot_notaionContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
